"""Turn a static finding into a runnable concurrency reproducer.

The value of a race report to a maintainer is roughly proportional to how fast
they can run it themselves.  For the finding shapes where the race has an
observable invariant -- a singleton that must be created once, a counter whose
increments must all land, a cache that must hand every caller the same object --
we can emit a self-contained script that either proves the race or exits clean.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass

from .model import Finding

_HEADER = '''#!/usr/bin/env python3
"""Auto-generated by ftaudit from {rule} at {path}:{line}.

    {message}

{why}

Run it on a free-threaded build, then again with PYTHON_GIL=1 to show the
difference the GIL was hiding:

    python3.14t {outname}
    PYTHON_GIL=1 python3.14t {outname}

Exit status 0 means no race was observed in this run; 1 means the invariant
below was violated.
"""

import sys
import threading

sys.path.insert(0, {module_root!r})

import {module} as target
'''

_FOOTER = '''

if __name__ == "__main__":
    raise SystemExit(main())
'''

_TEMPLATES: dict[str, str] = {
    "FT102": '''
SYMBOL = {symbol!r}
THREADS = {threads}
TRIALS = {trials}


def reset():
    """Put the module back into its pre-initialised state."""
    target.{attr} = None


def main():
    violations = []
    for trial in range(TRIALS):
        reset()
        barrier = threading.Barrier(THREADS)
        results = [None] * THREADS

        def worker(i):
            barrier.wait()
            results[i] = target.{accessor}()

        threads = [threading.Thread(target=worker, args=(i,)) for i in range(THREADS)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()

        distinct = {{id(r) for r in results}}
        if len(distinct) > 1:
            violations.append(
                f"trial {{trial}}: {{len(distinct)}} distinct objects returned from "
                f"{{THREADS}} concurrent calls -- the initialiser ran {{len(distinct)}} times"
            )

    print(f"python={{sys.version.split()[0]}} gil_enabled={{sys._is_gil_enabled()}}")
    print(f"{{SYMBOL}}: {{len(violations)}}/{{TRIALS}} trials raced")
    for v in violations[:5]:
        print("  " + v)
    return 1 if violations else 0
''',
    "FT105": '''
SYMBOL = {symbol!r}
THREADS = {threads}
ITERATIONS = {iterations}


def reset():
    target.{attr} = 0


def main():
    reset()
    barrier = threading.Barrier(THREADS)

    def worker():
        barrier.wait()
        for _ in range(ITERATIONS):
            target.{accessor}()

    threads = [threading.Thread(target=worker) for _ in range(THREADS)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()

    expected = THREADS * ITERATIONS
    observed = target.{attr}
    print(f"python={{sys.version.split()[0]}} gil_enabled={{sys._is_gil_enabled()}}")
    print(f"{{SYMBOL}}: expected {{expected}}, observed {{observed}}, lost {{expected - observed}}")
    return 1 if observed != expected else 0
''',
    "FT109": '''
SYMBOL = {symbol!r}
THREADS = {threads}
ITERATIONS = {iterations}


def main():
    barrier = threading.Barrier(THREADS)
    buckets = [[] for _ in range(THREADS)]

    def worker(i):
        barrier.wait()
        out = buckets[i]
        for _ in range(ITERATIONS):
            try:
                out.append(target.{accessor}())
            except (StopIteration, ValueError):
                return

    threads = [threading.Thread(target=worker, args=(i,)) for i in range(THREADS)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()

    values = [v for b in buckets for v in b]
    seen, dupes = set(), set()
    for v in values:
        if v in seen:
            dupes.add(v)
        seen.add(v)
    print(f"python={{sys.version.split()[0]}} gil_enabled={{sys._is_gil_enabled()}}")
    print(f"{{SYMBOL}}: {{len(values)}} values produced, {{len(dupes)}} duplicated")
    return 1 if dupes else 0
''',
}


@dataclass
class Generated:
    finding: Finding
    path: str
    kind: str


def _identifier(name: str) -> str | None:
    return name if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name) else None


def can_generate(finding: Finding) -> bool:
    return finding.rule in _TEMPLATES and _identifier(finding.symbol.split(".")[-1]) is not None


def generate(
    finding: Finding,
    module: str,
    module_root: str,
    out_dir: str,
    *,
    accessor: str | None = None,
    threads: int = 16,
    iterations: int = 5000,
    trials: int = 50,
) -> Generated | None:
    """Emit a reproducer for `finding`; returns None if the shape is unsupported.

    `accessor` is the public function that exercises the racy slot.  When it is
    not given we fall back to the enclosing function the finding was found in,
    which is right for module-level helpers such as ``get_instance``.
    """
    if not can_generate(finding):
        return None
    attr = _identifier(finding.symbol.split(".")[-1])
    fn = accessor or finding.function.split(".")[-1]
    if _identifier(fn) is None or attr is None:
        return None

    outname = f"repro_{finding.rule.lower()}_{attr.strip('_') or 'state'}.py"
    outpath = os.path.join(out_dir, outname)
    body = _TEMPLATES[finding.rule].format(
        symbol=finding.symbol,
        attr=attr,
        accessor=fn,
        threads=threads,
        iterations=iterations,
        trials=trials,
    )
    header = _HEADER.format(
        rule=finding.rule,
        path=finding.path,
        line=finding.line,
        message=finding.message,
        why="\n".join("    " + l for l in finding.why.split(". ")),
        module=module,
        module_root=module_root,
        outname=outname,
    )
    os.makedirs(out_dir, exist_ok=True)
    with open(outpath, "w", encoding="utf-8") as fh:
        fh.write(header + body + _FOOTER)
    os.chmod(outpath, 0o755)
    return Generated(finding=finding, path=outpath, kind=finding.rule)
